[package]
name = "cosmic-ext-ascii-dot-battery"
version = "1.2.0"
edition = "2021"
license = "MPL-2.0"
description = "Battery style applet for cosmic desktop"

repository = "https://github.com/your-username/cosmic-ext-ascii-dot-battery"

[build-dependencies]
xdgen = "0.1"

[dependencies]
i18n-embed-fl = "0.10"
rust-embed = "8.11"
tokio = { version = "1.52", features = ["rt-multi-thread", "time", "macros"] }
zbus = { version = "5", features = ["blocking-api"] }
starship-battery = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[dependencies.i18n-embed]
version = "0.16"
features = ["fluent-system", "desktop-requester"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
features = [
    "applet",
    "applet-token",
    "dbus-config",
    "multi-window",
]